name: Building Dynamic GSI..

on:
   pull_request:
   push:
     branches:
       - master

env:
  ROM_URL: https://dl.google.com/dl/android/aosp/redfin-rq1d.201205.012.a1-factory-c7ccc45f.zip
  ROM_NAME: Pixel
  FZIPNAME: redfin-rq1d.201205.012.a1-factory-c7ccc45f.zip
  ZIP_NAME: Pixel_dynamic
  TZ: Asia/Kolkata
  MIR: wet
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q` &> /dev/null
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d &> /dev/null
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* &> /dev/null
           sudo -E apt-get update &> /dev/null
           sudo -E apt-get -y autoremove --purge &> /dev/null
           sudo -E apt-get clean &> /dev/null
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update &> /dev/null
            sudo -E apt-get -qq install git openjdk-8-jdk wget expect &> /dev/null 

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/nnippon/ErfanGSIs.git &> /dev/null
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh &> /dev/null
       
       - name: Dynamic Setup
         run: |
              cd ErfanGSIs
              wget $ROM_URL &> /dev/null
              mkdir working
              mkdir output
              sudo bash dyn.sh $ROM_NAME $FZIPNAME
              sudo bash make.sh working/system $ROM_NAME AB output && sudo bash make.sh working/system $ROM_NAME Aonly output
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt
       - name   : Zip AB and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z  
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
         
            
            
